site_name: RAG-VisualRec
site_url: https://recsys-lab.github.io/rag-visualrec
repo_url: https://github.com/recsys-lab/rag-visualrec
repo_name: RecSys-lab/RAG-VisualRec
theme:
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  name: mkdocs
  palette:
    # Dark Mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: mkdocs/weather-sunny
        name: light mode
    # Light Mode
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: mkdocs/weather-night
        name: dark mode
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - pymdownx.details
  # - pymdownx.superfences
  # - pymdownx.blocks.caption
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
